spring:
  rabbitmq:
      addresses: localhost:19983
      username: rabbit
      password: 12345
      virtual-host: /
  profiles:
    active: true

server:
  port: 19980

phorest:
  events:
    configuration:
      rabbit:
        retry:
          maxRetryAttempts: 2
          minDelay: 1
          maxDelay: 1