server:
  port: 19980

phorest:
  events:
    configuration:
      rabbit:
        enabled: true
        addresses: localhost:32787
        username: rabbit
        password: 12345
        virtualHost: /
